/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/examples/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: ["class", "dark-theme"],
  theme: {
    extend: {
      colors: {
        background: {
          DEFAULT: "var(--base1)",
          1: "var(--base1)",
          2: "var(--base2)",
          3: "var(--base3)",
          4: "var(--base4)",
        },
        foreground: "var(--base12)",
        placeholder: "var(--base10)",
        border: "var(--base6)",
        ring: "var(--base8)",
        hover: "var(--accent4)",
        focus: "var(--accent4)",
        active: "var(--accent5)",
        unchecked: "var(--accent7)",
        checked: "var(--accent10)",
        base: {
          DEFAULT: "var(--base12)",
          1: "var(--base1)",
          2: "var(--base2)",
          3: "var(--base3)",
          4: "var(--base4)",
          5: "var(--base5)",
          6: "var(--base6)",
          7: "var(--base7)",
          8: "var(--base8)",
          9: "var(--base9)",
          10: "var(--base10)",
          11: "var(--base11)",
          12: "var(--base12)",
        },
        accent: {
          DEFAULT: "var(--accent12)",
          1: "var(--accent1)",
          2: "var(--accent2)",
          3: "var(--accent3)",
          4: "var(--accent4)",
          5: "var(--accent5)",
          6: "var(--accent6)",
          7: "var(--accent7)",
          8: "var(--accent8)",
          9: "var(--accent9)",
          10: "var(--accent10)",
          11: "var(--accent11)",
          12: "var(--accent12)",
        },
        white: {
          DEFAULT: "var(--whiteA12)",
          1: "var(--whiteA1)",
          2: "var(--whiteA2)",
          3: "var(--whiteA3)",
          4: "var(--whiteA4)",
          5: "var(--whiteA5)",
          6: "var(--whiteA6)",
          7: "var(--whiteA7)",
          8: "var(--whiteA8)",
          9: "var(--whiteA9)",
          10: "var(--whiteA10)",
          11: "var(--whiteA11)",
          12: "var(--whiteA12)",
        },
        black: {
          DEFAULT: "var(--blackA12)",
          1: "var(--blackA1)",
          2: "var(--blackA2)",
          3: "var(--blackA3)",
          4: "var(--blackA4)",
          5: "var(--blackA5)",
          6: "var(--blackA6)",
          7: "var(--blackA7)",
          8: "var(--blackA8)",
          9: "var(--blackA9)",
          10: "var(--blackA10)",
          11: "var(--blackA11)",
          12: "var(--blackA12)",
        },
        blue: {
          1: "var(--blue1)",
          2: "var(--blue2)",
          3: "var(--blue3)",
          4: "var(--blue4)",
          5: "var(--blue5)",
          6: "var(--blue6)",
          7: "var(--blue7)",
          8: "var(--blue8)",
          9: "var(--blue9)",
          10: "var(--blue10)",
          11: "var(--blue11)",
          12: "var(--blue12)",
        },
        green: {
          1: "var(--green1)",
          2: "var(--green2)",
          3: "var(--green3)",
          4: "var(--green4)",
          5: "var(--green5)",
          6: "var(--green6)",
          7: "var(--green7)",
          8: "var(--green8)",
          9: "var(--green9)",
          10: "var(--green10)",
          11: "var(--green11)",
          12: "var(--green12)",
        },
        yellow: {
          1: "var(--yellow1)",
          2: "var(--yellow2)",
          3: "var(--yellow3)",
          4: "var(--yellow4)",
          5: "var(--yellow5)",
          6: "var(--yellow6)",
          7: "var(--yellow7)",
          8: "var(--yellow8)",
          9: "var(--yellow9)",
          10: "var(--yellow10)",
          11: "var(--yellow11)",
          12: "var(--yellow12)",
        },
        red: {
          1: "var(--red1)",
          2: "var(--red2)",
          3: "var(--red3)",
          4: "var(--red4)",
          5: "var(--red5)",
          6: "var(--red6)",
          7: "var(--red7)",
          8: "var(--red8)",
          9: "var(--red9)",
          10: "var(--red10)",
          11: "var(--red11)",
          12: "var(--red12)",
        },
      },
    },
  },
  plugins: [require("@tailwindcss/container-queries")],
};
