import "./globals.css";
import { ThemeProvider } from "@components/providers/ThemeProvider";
import { ToastProvider } from "@components/providers/ToastProvider";
import { TooltipProvider } from "@components/ui/Tooltip";

import { Body } from "@components/layout/Body";
import { Navbar } from "@components/layout/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <Body>
          <TooltipProvider>
            <ToastProvider>
              <Navbar />
              <main className="mx-auto grid min-h-screen w-full max-w-4xl px-4 py-8">
                {children}
              </main>
            </ToastProvider>
          </TooltipProvider>
        </Body>
      </ThemeProvider>
    </html>
  );
}
